services:

  xpense:
    image: xpense03
    ports:
      - "5000:5000"
    expose:
      - "5000"
    env_file: .env
    depends_on:
      db_finance:
        condition: service_healthy

  db_finance:
    image: db_finance
    restart: always
    ports:
      - "5433:5433"
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 15s
      retries: 3
      start_period: 20s

  nosql_db_finance:
    image: mongo
    env_file: .env
    ports:
      - "27017:27017"